// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as Layoutlayout2Import } from './routes/_layout/_layout-2'
import { Route as Layoutlayout2LayoutBImport } from './routes/_layout/_layout-2/layout-b'
import { Route as Layoutlayout2LayoutAImport } from './routes/_layout/_layout-2/layout-a'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const Layoutlayout2Route = Layoutlayout2Import.update({
  id: '/_layout-2',
  getParentRoute: () => LayoutRoute,
} as any)

const Layoutlayout2LayoutBRoute = Layoutlayout2LayoutBImport.update({
  path: '/layout-b',
  getParentRoute: () => Layoutlayout2Route,
} as any)

const Layoutlayout2LayoutARoute = Layoutlayout2LayoutAImport.update({
  path: '/layout-a',
  getParentRoute: () => Layoutlayout2Route,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_layout-2': {
      preLoaderRoute: typeof Layoutlayout2Import
      parentRoute: typeof LayoutImport
    }
    '/_layout/_layout-2/layout-a': {
      preLoaderRoute: typeof Layoutlayout2LayoutAImport
      parentRoute: typeof Layoutlayout2Import
    }
    '/_layout/_layout-2/layout-b': {
      preLoaderRoute: typeof Layoutlayout2LayoutBImport
      parentRoute: typeof Layoutlayout2Import
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    Layoutlayout2Route.addChildren([
      Layoutlayout2LayoutARoute,
      Layoutlayout2LayoutBRoute,
    ]),
  ]),
])
